import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, AlertTriangle, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { storage } from '../services/storage';
import type { ComprehensiveAnalysis } from '../types';

type WizardStep = 'setup' | 'analyzing' | 'results' | 'export';

export const AcademicWizard: React.FC = () => {
  const [step, setStep] = useState<WizardStep>('setup');
  const [conceptName, setConceptName] = useState('');
  const [jurisdiction, setJurisdiction] = useState('');
  const [researchQuestion, setResearchQuestion] = useState('');
  const [includeGenealogy, setIncludeGenealogy] = useState(true);
  const [includeNetwork, setIncludeNetwork] = useState(false);
  const [realityFilterEnabled] = useState(true); // Always enabled
  
  const [analysis, setAnalysis] = useState<ComprehensiveAnalysis | null>(null);
  const [report, setReport] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  const handleStartAnalysis = async () => {
    if (!conceptName.trim() || !jurisdiction.trim()) {
      setError('Please fill in all required fields');
      return;
    }

    setStep('analyzing');
    setError(null);

    try {
      // Run comprehensive analysis
      const analysisResult = await api.analyzeComprehensive({
        concept_name: conceptName,
        jurisdiction,
        include_genealogy: includeGenealogy,
        include_network: includeNetwork,
      });

      if (!analysisResult.success || !analysisResult.data) {
        throw new Error('Analysis failed');
      }

      // Generate report
      const reportResult = await api.generateAnalysisReport({
        concept_name: conceptName,
        jurisdiction,
        include_genealogy: includeGenealogy,
        include_network: includeNetwork,
      });

      setAnalysis(analysisResult.data);
      setReport(reportResult.report || '');
      setStep('results');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Analysis failed');
      setStep('setup');
    }
  };

  const handleSave = () => {
    if (!analysis) return;

    storage.saveAnalysis({
      type: 'comprehensive',
      title: `${conceptName} - Academic Analysis`,
      description: researchQuestion || `Comprehensive analysis of ${conceptName} in ${jurisdiction}`,
      data: analysis,
      tags: ['academic', 'comprehensive', jurisdiction.toLowerCase()],
    });

    alert('Analysis saved to workspace!');
  };

  const handleExport = (format: 'pdf' | 'latex' | 'json') => {
    if (!analysis) return;

    let content = '';
    let filename = '';
    let mimeType = '';

    switch (format) {
      case 'json':
        content = JSON.stringify({ analysis, report }, null, 2);
        filename = `analysis_${conceptName.replace(/\s+/g, '_')}_${Date.now()}.json`;
        mimeType = 'application/json';
        break;
      case 'latex':
        // Generate basic LaTeX structure
        content = generateLaTeX(analysis, report);
        filename = `analysis_${conceptName.replace(/\s+/g, '_')}_${Date.now()}.tex`;
        mimeType = 'application/x-latex';
        break;
      case 'pdf':
        // For PDF, we'll just download the report as text for now
        // In production, you'd use a proper PDF generation library
        content = report;
        filename = `analysis_${conceptName.replace(/\s+/g, '_')}_${Date.now()}.txt`;
        mimeType = 'text/plain';
        break;
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateLaTeX = (analysis: ComprehensiveAnalysis, report: string): string => {
    return `\\documentclass[12pt]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{booktabs}
\\usepackage{graphicx}
\\usepackage{hyperref}

\\title{Legal Analysis: ${conceptName}}
\\author{Generated by Legal Evolution Unified}
\\date{${new Date().toISOString().split('T')[0]}}

\\begin{document}

\\maketitle

\\section{Abstract}
Comprehensive legal analysis of "${conceptName}" in ${jurisdiction}.

\\section{Fitness Analysis}
\\begin{itemize}
\\item Fitness Score: ${analysis.fitness.fitness.toFixed(4)}
\\item 95\\% CI: [${analysis.fitness.ci_lower.toFixed(4)}, ${analysis.fitness.ci_upper.toFixed(4)}]
\\item Statistical Significance: ${analysis.fitness.significant ? 'YES' : 'NO'} (p=${analysis.fitness.p_value.toFixed(4)})
\\item Bootstrap Iterations: ${analysis.fitness.n_bootstrap_samples}
\\end{itemize}

${analysis.genealogy ? `
\\section{Genealogical Analysis}
\\begin{itemize}
\\item Ancestors: ${analysis.genealogy.ancestors.length}
\\item Descendants: ${analysis.genealogy.descendants.length}
\\item Graph Nodes: ${analysis.genealogy.graph_nodes}
\\item Graph Edges: ${analysis.genealogy.graph_edges}
\\end{itemize}
` : ''}

\\section{Full Report}
\\begin{verbatim}
${report}
\\end{verbatim}

\\end{document}`;
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-gradient-to-r from-purple-600 to-purple-800 text-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <div className="flex items-center gap-4">
            <Link
              to="/"
              className="p-2 hover:bg-white/20 rounded-lg transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div>
              <h1 className="text-2xl font-serif font-bold">
                Academic Analysis Wizard
              </h1>
              <p className="text-purple-100 text-sm">
                Publication-ready analysis with Reality Filter
              </p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-8">
        {/* Progress Steps */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            {['Setup', 'Analyzing', 'Results', 'Export'].map((label, idx) => {
              const stepNames: WizardStep[] = ['setup', 'analyzing', 'results', 'export'];
              const currentStepIdx = stepNames.indexOf(step);
              const isActive = idx === currentStepIdx;
              const isCompleted = idx < currentStepIdx;

              return (
                <React.Fragment key={label}>
                  <div className="flex flex-col items-center">
                    <div
                      className={`w-12 h-12 rounded-full flex items-center justify-center font-bold transition-all ${
                        isCompleted
                          ? 'bg-green-500 text-white'
                          : isActive
                          ? 'bg-purple-600 text-white'
                          : 'bg-gray-200 text-gray-500'
                      }`}
                    >
                      {isCompleted ? <Check className="w-6 h-6" /> : idx + 1}
                    </div>
                    <span className="text-sm mt-2 font-medium">{label}</span>
                  </div>
                  {idx < 3 && (
                    <div
                      className={`flex-1 h-1 mx-4 ${
                        idx < currentStepIdx ? 'bg-green-500' : 'bg-gray-200'
                      }`}
                    />
                  )}
                </React.Fragment>
              );
            })}
          </div>
        </div>

        {/* Step 1: Setup */}
        {step === 'setup' && (
          <div className="card">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">
              Configure Analysis
            </h2>

            {error && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                <p className="text-red-800">{error}</p>
              </div>
            )}

            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Legal Concept <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={conceptName}
                  onChange={(e) => setConceptName(e.target.value)}
                  placeholder="e.g., Habeas Corpus, Due Process, Sovereignty"
                  className="input-field"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Jurisdiction <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={jurisdiction}
                  onChange={(e) => setJurisdiction(e.target.value)}
                  placeholder="e.g., United States, European Union"
                  className="input-field"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Research Question (Optional)
                </label>
                <textarea
                  value={researchQuestion}
                  onChange={(e) => setResearchQuestion(e.target.value)}
                  placeholder="What research question are you exploring?"
                  className="input-field h-24 resize-none"
                />
              </div>

              <div className="border-t pt-6">
                <h3 className="font-semibold text-gray-900 mb-4">
                  Analysis Components
                </h3>

                <div className="space-y-3">
                  <label className="flex items-center gap-3 p-4 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50">
                    <input
                      type="checkbox"
                      checked={includeGenealogy}
                      onChange={(e) => setIncludeGenealogy(e.target.checked)}
                      className="w-5 h-5 text-purple-600"
                    />
                    <div className="flex-1">
                      <div className="font-medium text-gray-900">
                        Genealogical Analysis (RootFinder)
                      </div>
                      <div className="text-sm text-gray-600">
                        Trace ancestors and descendants of the concept
                      </div>
                    </div>
                  </label>

                  <label className="flex items-center gap-3 p-4 border border-gray-200 rounded-lg cursor-pointer hover:bg-gray-50">
                    <input
                      type="checkbox"
                      checked={includeNetwork}
                      onChange={(e) => setIncludeNetwork(e.target.checked)}
                      className="w-5 h-5 text-purple-600"
                    />
                    <div className="flex-1">
                      <div className="font-medium text-gray-900">
                        Network Analysis (Peralta)
                      </div>
                      <div className="text-sm text-gray-600">
                        PageRank, centrality metrics, community detection
                      </div>
                    </div>
                  </label>

                  <div className="p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
                    <input
                      type="checkbox"
                      checked={realityFilterEnabled}
                      disabled
                      className="w-5 h-5 text-red-600 mt-0.5"
                    />
                    <div className="flex-1">
                      <div className="font-medium text-red-900">
                        Reality Filter (Mandatory)
                      </div>
                      <div className="text-sm text-red-800">
                        Verifies all claims against real legal sources to prevent
                        hallucinations
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-8 flex justify-end">
              <button
                onClick={handleStartAnalysis}
                className="btn-primary flex items-center gap-2"
              >
                Start Analysis
                <ArrowRight className="w-5 h-5" />
              </button>
            </div>
          </div>
        )}

        {/* Step 2: Analyzing */}
        {step === 'analyzing' && (
          <div className="card">
            <div className="text-center py-12">
              <div className="inline-block animate-spin rounded-full h-16 w-16 border-4 border-purple-200 border-t-purple-600 mb-6"></div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">
                Running Comprehensive Analysis
              </h2>
              <p className="text-gray-600 mb-4">
                This may take 1-2 minutes...
              </p>
              <div className="max-w-md mx-auto space-y-2 text-left text-sm text-gray-600">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-purple-600 rounded-full animate-pulse"></div>
                  <span>Calculating legal fitness (JurisRank)...</span>
                </div>
                {includeGenealogy && (
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-purple-600 rounded-full animate-pulse"></div>
                    <span>Tracing genealogy (RootFinder)...</span>
                  </div>
                )}
                {includeNetwork && (
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-purple-600 rounded-full animate-pulse"></div>
                    <span>Analyzing network position (Peralta)...</span>
                  </div>
                )}
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-red-600 rounded-full animate-pulse"></div>
                  <span>Applying Reality Filter...</span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Step 3: Results */}
        {step === 'results' && analysis && (
          <div className="space-y-6">
            {/* Summary Card */}
            <div className="card bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                Analysis Complete!
              </h2>
              <div className="grid md:grid-cols-3 gap-6">
                <div>
                  <div className="text-3xl font-bold text-purple-600 mb-1">
                    {analysis.fitness.fitness.toFixed(3)}
                  </div>
                  <div className="text-gray-700 font-medium">Fitness Score</div>
                  <div className="text-sm text-gray-600">
                    {analysis.fitness.significant ? 'Statistically significant' : 'Not significant'}
                  </div>
                </div>
                {analysis.genealogy && (
                  <div>
                    <div className="text-3xl font-bold text-amber-600 mb-1">
                      {analysis.genealogy.ancestors.length + analysis.genealogy.descendants.length}
                    </div>
                    <div className="text-gray-700 font-medium">Genealogical Links</div>
                    <div className="text-sm text-gray-600">
                      {analysis.genealogy.ancestors.length} ancestors, {analysis.genealogy.descendants.length} descendants
                    </div>
                  </div>
                )}
                {analysis.network && (
                  <div>
                    <div className="text-3xl font-bold text-blue-600 mb-1">
                      {(analysis.network.metrics.pagerank || 0).toFixed(4)}
                    </div>
                    <div className="text-gray-700 font-medium">PageRank</div>
                    <div className="text-sm text-gray-600">
                      Network influence score
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Report */}
            <div className="card">
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Full Analysis Report
              </h3>
              <div className="bg-gray-50 p-6 rounded-lg border border-gray-200 font-mono text-sm overflow-x-auto">
                <pre className="whitespace-pre-wrap">{report}</pre>
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3">
              <button onClick={handleSave} className="btn-secondary">
                Save to Workspace
              </button>
              <button onClick={() => setStep('export')} className="btn-primary">
                Export Report
              </button>
            </div>
          </div>
        )}

        {/* Step 4: Export */}
        {step === 'export' && (
          <div className="card">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">
              Export Analysis
            </h2>
            <p className="text-gray-600 mb-6">
              Choose format for your academic publication:
            </p>

            <div className="grid md:grid-cols-3 gap-4 mb-8">
              <button
                onClick={() => handleExport('pdf')}
                className="p-6 border-2 border-gray-200 rounded-xl hover:border-purple-500 hover:shadow-lg transition-all text-center group"
              >
                <FileText className="w-12 h-12 mx-auto mb-3 text-gray-400 group-hover:text-purple-600" />
                <div className="font-bold text-gray-900">PDF Report</div>
                <div className="text-sm text-gray-600 mt-1">
                  Publication-ready document
                </div>
              </button>

              <button
                onClick={() => handleExport('latex')}
                className="p-6 border-2 border-gray-200 rounded-xl hover:border-purple-500 hover:shadow-lg transition-all text-center group"
              >
                <FileText className="w-12 h-12 mx-auto mb-3 text-gray-400 group-hover:text-purple-600" />
                <div className="font-bold text-gray-900">LaTeX Source</div>
                <div className="text-sm text-gray-600 mt-1">
                  For journal submissions
                </div>
              </button>

              <button
                onClick={() => handleExport('json')}
                className="p-6 border-2 border-gray-200 rounded-xl hover:border-purple-500 hover:shadow-lg transition-all text-center group"
              >
                <FileText className="w-12 h-12 mx-auto mb-3 text-gray-400 group-hover:text-purple-600" />
                <div className="font-bold text-gray-900">JSON Data</div>
                <div className="text-sm text-gray-600 mt-1">
                  Raw analysis data
                </div>
              </button>
            </div>

            <div className="flex justify-between">
              <button
                onClick={() => setStep('results')}
                className="btn-secondary flex items-center gap-2"
              >
                <ArrowLeft className="w-5 h-5" />
                Back to Results
              </button>
              <Link to="/workspace" className="btn-primary">
                Go to Workspace
              </Link>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default AcademicWizard;
